apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
  - image: kubia-unhealthy-image:latest
    name: kubia
    livenessProbe:
      httpGet:
        path: /
        port: 8080

